name = "example"
print ( name [0])
print ( name [-1])
print ('urban' [2:5])
print ('urban' [::-1])
print ('Топинамбур' [1::2] )
print ('Топинамбур'[0])
print ('Топинамбур'[-1])
print ('Топинамбур'[5:9])
print ('Топинамбур'[::-1])
print ('Топинамбур'[1::2])
